# Generated by Django 2.2.3 on 2019-07-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
