# Generated by Django 2.2.2 on 2019-07-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_article_stars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Select', max_length=40),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='select'),
        ),
    ]
