# Generated by Django 2.2.4 on 2019-08-07 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='obj_sum',
            field=models.ManyToManyField(blank=True, related_name='obj_users', to='article.Summary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sbj_sum',
            field=models.ManyToManyField(blank=True, related_name='sbj_users', to='article.Summary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
