# Generated by Django 2.2.3 on 2019-08-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190728_2021'),
        ('accounts', '0002_auto_20190729_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='obj_summ',
            field=models.ManyToManyField(blank=True, related_name='obj_users', to='article.Summary'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sbj_summ',
            field=models.ManyToManyField(blank=True, related_name='sbj_users', to='article.Summary'),
        ),
    ]
