# Generated by Django 2.2.3 on 2019-08-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190807_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
