# Generated by Django 2.2.3 on 2019-08-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('accounts', '0003_auto_20190806_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
