# Generated by Django 2.2.3 on 2019-07-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='article_id',
            new_name='belongsto_article',
        ),
    ]
