# Generated by Django 2.2.3 on 2019-08-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190808_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='original',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
