# Generated by Django 2.2.3 on 2019-08-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190808_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Tons\\static\\img'),
        ),
    ]
