# Generated by Django 2.2.3 on 2019-08-09 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190808_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'Summaries'},
        ),
    ]
