# Generated by Django 2.2.4 on 2019-08-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190809_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'get_latest_by': 'obj_count', 'ordering': ['-pub_date'], 'verbose_name_plural': 'Summaries'},
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media\\img'),
        ),
    ]
