# Generated by Django 2.2.4 on 2019-08-09 14:41

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190809_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='article/thumbnails/%Y/%m', verbose_name='Thumbnail'),
        ),
    ]
