# Generated by Django 2.2.4 on 2019-08-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20190809_2343'),
        ('article', '0010_auto_20190809_2354'),
    ]

    operations = [
    ]
