# Generated by Django 2.2.4 on 2019-08-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20190810_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stars_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
